# Generated by Django 5.2.17 on 2026-09-11 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.CharField(default='10:00', max_length=10)),
                ('end_time', models.CharField(default='11:00', max_length=10)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('processed', 'Обработано')], default='in_progress', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_recordings/')),
                ('audio_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('assignee', models.CharField(default='Не назначен', max_length=255)),
                ('deadline', models.CharField(blank=True, default='', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'К исполнению'), ('in_progress', 'В работе'), ('completed', 'Выполнено')], default='pending', max_length=20)),
                ('source_timestamp', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='api.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(default='spk-1', max_length=50)),
                ('speaker_name', models.CharField(default='Спикер 1', max_length=100)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('text', models.TextField()),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.meeting')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(default='Участник совещаний', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
